"""add_soil_moisture

Revision ID: 069fa0c40831
Revises: 523fc5db27ef
Create Date: 2026-08-14 16:12:46.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '069fa0c40831'
down_revision: Union[str, None] = '523fc5db27ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weather_events', sa.Column('soil_moisture_m3_m3', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('weather_events', 'soil_moisture_m3_m3')
    # ### end Alembic commands ###
