"""add sar_status and ms_status to analysis_jobs

Revision ID: 5027e95b6563
Revises: a157ea16baf9
Create Date: 2026-08-14 09:55:49.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5027e95b6563'
down_revision: Union[str, None] = 'a157ea16baf9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('sar_status', sa.String(), nullable=True))
    op.add_column('analysis_jobs', sa.Column('ms_status', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'ms_status')
    op.drop_column('analysis_jobs', 'sar_status')
    # ### end Alembic commands ###
