"""add_weather_status

Revision ID: 523fc5db27ef
Revises: 5027e95b6563
Create Date: 2026-08-14 16:01:46.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '523fc5db27ef'
down_revision: Union[str, None] = '5027e95b6563'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('weather_status', sa.String(), nullable=True, server_default='queued'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'weather_status')
    # ### end Alembic commands ###
