"""Add error_message to analysis_jobs

Revision ID: a157ea16baf9
Revises: bca3aee1129b
Create Date: 2026-08-13 19:52:19.467368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a157ea16baf9'
down_revision: Union[str, None] = 'cc10ab1567bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('error_message', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_jobs', 'error_message')
    # ### end Alembic commands ###
